version: '3.8'

networks:
  llama-net:
    driver: bridge

volumes:
  ollama_data:

services:
  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    container_name: ollama
    restart: unless-stopped
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    networks:
      - llama-net

    # ─── GPU support (optional) ────────────────────────────────────────────
    # (Requires nvidia‐container‐runtime / Docker 19.03+)
    runtime: nvidia
    gpus: all
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    # ────────────────────────────────────────────────────────────────────────

    entrypoint: ["ollama", "serve"]

  llama-rag:
    build:
      context: ./app
    container_name: llama-rag
    depends_on:
      - ollama
    networks:
      - llama-net
    volumes:
      - ./app:/app:cached
    working_dir: /app
    ports:
      - "8501:8501"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    command: ["streamlit", "run", "main.py"]
    restart: unless-stopped
